services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    stdin_open: true  # Docker Compose equivalent of -i
    tty: true         # Docker Compose equivalent of -t
    command: sbt

  app-prod:
    build: .
    ports:
      - "8080:8080"
    command: sbt run