name: "Deploy with CDK"
description: "Deploy infrastructure and services using AWS CDK"
inputs:
  region:
    description: "AWS region to deploy to"
    required: true
  registry:
    description: "Docker registry URL"
    required: true
  repository:
    description: "Docker repository name"
    required: true
  aws_access_key_id:
    description: "AWS Access Key ID"
    required: true
  aws_secret_access_key:
    description: "AWS Secret Access Key"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: CDK prepare
      working-directory: ./infrastructure
      shell: bash
      run: npm ci

    - name: Deploy with CDK
      working-directory: ./infrastructure
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        REPOSITORY: ${{ inputs.repository }}
        IMAGE_TAG: ${{ github.sha }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        AWS_REGION: ${{ inputs.region }}
      run: |
        if ! command -v cdk &> /dev/null; then
          npm install -g aws-cdk
        fi
        cdk synth
        cdk deploy --all --require-approval never --outputs-file cdk-outputs.json
