name: "Push Docker Image"
description: "Pushes a Docker image to ECR"
inputs:
  registry:
    description: "Docker registry URL"
    required: true
  repository:
    description: "Docker repository name"
    required: true
  git_sha:
    description: "Git SHA of the image to push"
    required: true
  region:
    description: "AWS region"
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.region }}

    - name: Download Docker Image
      uses: actions/download-artifact@v4
      with:
        name: docker-image

    - name: Load and Push Docker Image
      shell: bash
      run: |
        docker load -i image.tar
        aws ecr get-login-password --region ${{ inputs.region }} | docker login --username AWS --password-stdin ${{ inputs.registry }}
        docker tag ${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.git_sha }} ${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.git_sha }}
        docker push ${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.git_sha }}
