name: Build & Deploy

on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS region to deploy to"
        type: choice
        options:
          - us-east-2
        default: "us-east-2"
      stage:
        description: "AWS environment to deploy to"
        type: choice
        options:
          - prod
        default: "prod"
      desired_fargate_task_count:
        description:
          "Desired count of Fargate tasks" # e.g., 0 to scale down, 1 to scale up
        required: false
        default: "1"

env:
  REGISTRY: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.region }}.amazonaws.com"
  REPOSITORY: "theproductcollectiveco/play4s-service-${{ inputs.stage }}"

jobs:
  build-and-publish:
    name: Build & Publish Artifact Locally
    uses: ./.github/workflows/build-image.yml 
    with:
      region: ${{ inputs.region }}
      stage: ${{ inputs.stage }}
    secrets: inherit

  push-to-ecr:
    name: Push Image Artifact
    runs-on: ubuntu-latest
    needs:
      - build-and-publish

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Push Docker Image
        uses: ./.github/actions/push
        with:
          registry: ${{ env.REGISTRY }}
          repository: ${{ env.REPOSITORY }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ inputs.region }}
          git_sha: ${{ github.sha }}

  deploy:
    name: Deploy CDK Resources
    runs-on: ubuntu-latest
    needs:
      - push-to-ecr
      - build-and-publish

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with CDK
        uses: ./.github/actions/deploy
        with:
          registry: ${{ env.REGISTRY }}
          repository: ${{ env.REPOSITORY }}
          git_sha: ${{ github.sha }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ inputs.region }}
          app_name: "play4s"
          stage: ${{ inputs.stage }}
          desired_fargate_task_count: ${{ inputs.desired_fargate_task_count }}