name: "Build: Reusable Workflow"

on:
  workflow_call:
    inputs:
      region:
        required: true
        type: string
      stage:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        uses: ./.github/actions/build
        with:
          registry: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.region || 'us-east-1' }}.amazonaws.com"
          repository:  "theproductcollectiveco/play4s-service"
          git_sha: ${{ github.sha }}
          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}