name: Push to ECR

on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS region to push to"
        type: choice
        options:
          - us-east-2
        default: "us-east-2"

env:
  REGISTRY: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.region }}.amazonaws.com"
  REPOSITORY: "theproductcollectiveco/play4s-service-prod"

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        uses: ./.github/actions/build
        with:
          registry: ${{ env.REGISTRY }}
          repository: ${{ env.REPOSITORY }}

      - name: Push Docker Image
        uses: ./.github/actions/push
        with:
          registry: ${{ env.REGISTRY }}
          repository: ${{ env.REPOSITORY }}
          region: ${{ inputs.region }}
