name: Push to ECR

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      region:
        description: "AWS region to deploy to"
        type: choice
        options:
          - us-east-1
        default: "us-east-1"
      stage:
        description: "AWS environment to deploy to"
        type: choice
        options:
          - prod
        default: "prod"

env:
  REGISTRY: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.region || 'us-east-1' }}.amazonaws.com"
  REPOSITORY: "theproductcollectiveco/play4s-service"

jobs:
  push-to-ecr:
    name: Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Push Docker Image
        uses: ./.github/actions/push
        with:
          registry: ${{ env.REGISTRY }}
          repository: ${{ env.REPOSITORY }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ inputs.region || 'us-east-1' }}
          git_sha: ${{ github.sha }}