name: Validate Build

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build & Publish Artifact Locally
    uses: ./.github/workflows/build.yml
    with:
      region: 'us-east-1'
      stage: 'prod'
    secrets: inherit