name: Validate Build

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build & Publish Artifact Locally
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build & Package Application
        uses: ./.github/actions/build
        with:
          registry: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ 'us-east-1' }}.amazonaws.com"
          repository: 'theproductcollectiveco/app-play4s-service-repository'
          git_sha: ${{ github.sha }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ 'us-east-1' }}