name: Validate Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-image.yml
    with:
      region: 'us-east-2'
      stage: 'prod'
    secrets: inherit